---
services:
  rag-llm:
    image: rag-llm:latest
    container_name: rag-llm
    pull_policy: never
    ports:
    - "8000:8000"
    restart: unless-stopped
    environment:
      OLLAMA_SERVER_URL: 'http://localhost:11434'
      WEAVIATE_SERVER_URL: 'localhost:8080'
      WEB_SERVER_PORT: ':8000'
      LLM_MODEL_NAME: 'llama3.2'
    tty: true
    networks:
    - internet
    depends_on:
    - ollama
    - weaviate
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    # ports:
    # - "11434:11434"
    restart: unless-stopped
    volumes:
    - ollama:/root/.ollama
    tty: true
    networks:
    - internet
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    container_name: weaviate
    pull_policy: always
    # ports:
    # - 8080:8080
    # - 50051:50051
    restart: unless-stopped
    volumes:
    - weaviate_data:/var/lib/weaviate
    tty: true
    networks:
    - internet
volumes:
  ollama: {}
  weaviate_data: {}
networks:
  internet:
    driver: bridge
